name: Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: Install dependencies
        working-directory: client
        run: npm ci

      - name: Build for production
        working-directory: client
        run: npm run build:github

      # --- FIX STARTS HERE ---

      - name: (Debug) List files in the build output
        run: ls -R ./client/dist/techtrek
        # This step helps you see the exact structure. You can remove it later.

      - name: Create a clean deployment directory
        run: mkdir ./deployment

      - name: Copy browser output to deployment directory
        run: cp -r ./client/dist/techtrek/browser/* ./deployment

      - name: Create .nojekyll file in the correct location
        run: touch ./deployment/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deployment

  deploy:
    if: github.event_name != 'pull_request'
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
