name: Deploy NestJS Backend

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**' 
      - '.github/workflows/nestjs-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Build NestJS Application
        run: npm run build

      - name: Create .env file for production
        run: |
          echo "NODE_ENV=production" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        if: success()

      - name: Deploy to Railway
        if: success()
        run: |
          # Install Railway CLI
          npm install -g @railway/cli
          
          # Deploy to Railway
          railway login --service-token ${{ secrets.RAILWAY_TOKEN }}
          railway up --service backend
          
          # Get the deployment URL
          BACKEND_URL=$(railway status --json | jq -r '.deployment.url')
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV
          echo "Backend deployed to: $BACKEND_URL"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Update Angular deployment with backend URL
        if: success()
        run: |
          # Trigger the Angular deployment with the backend URL
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"backend-deployed","client_payload":{"backend_url":"'$BACKEND_URL'"}}'

