name: Deploy NestJS Backend

on:
  push:
    branches:
      - main 
    paths:
      - 'backend/**' 
      - '.github/workflows/nestjs-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Build NestJS Application
        run: npm run build

      - name: Create .env file for production
        run: |
          echo "NODE_ENV=production" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        if: success()

      - name: Deploy to Railway
        if: success()
        run: |
          # Install Railway CLI
          npm install -g @railway/cli
          
          # Deploy to Railway (authentication via RAILWAY_TOKEN environment variable)
          railway up
          
          echo "Backend deployed successfully to Railway"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Trigger Angular deployment
        if: success()
        run: |
          # Get the backend URL from repository variables or use Railway URL
          BACKEND_URL="${{ vars.BACKEND_URL }}"
          
          if [ -z "$BACKEND_URL" ]; then
            echo "Warning: BACKEND_URL not set in repository variables. Please set it manually."
            BACKEND_URL="https://your-railway-app.railway.app"
          fi
          
          echo "Triggering Angular deployment with backend URL: $BACKEND_URL"
          
          # Trigger the Angular deployment with the backend URL
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"backend-deployed","client_payload":{"backend_url":"'$BACKEND_URL'"}}'

