name: Update Screenshots and README

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/screenshot-update.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  take-screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm ci

      - name: Install Playwright browsers
        working-directory: ./client
        run: npx playwright install --with-deps chromium

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Start Backend Server
        working-directory: ./backend
        run: |
          npm start &
          echo $! > backend.pid
          sleep 10
        env:
          NODE_ENV: production
          JWT_SECRET: test-secret-key
          DATABASE_URL: ":memory:"

      - name: Start Client Server
        working-directory: ./client
        run: |
          npx serve -s dist/techtrek -l 4200 &
          echo $! > client.pid
          sleep 5

      - name: Wait for servers to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000/health || curl -f http://localhost:3000; do sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:4200; do sleep 2; done'

      - name: Create screenshots directory
        run: mkdir -p screenshots

      - name: Create screenshot script
        run: |
          cat << 'EOF' > take-screenshots.js
          const { chromium } = require('playwright');
          const fs = require('fs');
          const path = require('path');

          async function takeScreenshots() {
            const browser = await chromium.launch();
            
            const pages = [
              {
                name: 'login',
                url: 'http://localhost:4200/login',
                waitFor: '[data-cy="login-card"]',
                actions: []
              },
              {
                name: 'clocking',
                url: 'http://localhost:4200/clocking',
                waitFor: '[data-cy="clocking-page"]',
                actions: [
                  async (page) => {
                    // Mock login by setting localStorage
                    await page.evaluate(() => {
                      localStorage.setItem('JWT_TOKEN', 'mock-jwt-token');
                      localStorage.setItem('CURRENT_USER', JSON.stringify({
                        id: 1,
                        username: 'demo@example.com',
                        email: 'demo@example.com'
                      }));
                    });
                  }
                ]
              },
              {
                name: 'holiday',
                url: 'http://localhost:4200/holiday',
                waitFor: '.holiday-planner-container',
                actions: [
                  async (page) => {
                    // Mock login by setting localStorage
                    await page.evaluate(() => {
                      localStorage.setItem('JWT_TOKEN', 'mock-jwt-token');
                      localStorage.setItem('CURRENT_USER', JSON.stringify({
                        id: 1,
                        username: 'demo@example.com',
                        email: 'demo@example.com'
                      }));
                    });
                  }
                ]
              }
            ];

            const themes = ['light', 'dark'];

            for (const pageDef of pages) {
              for (const theme of themes) {
                const context = await browser.newContext({
                  viewport: { width: 1280, height: 720 },
                  colorScheme: theme
                });
                
                const page = await context.newPage();
                
                // Mock API responses
                await page.route('**/api/**', route => {
                  const url = route.request().url();
                  if (url.includes('/clockings')) {
                    route.fulfill({
                      status: 200,
                      contentType: 'application/json',
                      body: JSON.stringify([])
                    });
                  } else if (url.includes('/holidays')) {
                    route.fulfill({
                      status: 200,
                      contentType: 'application/json',
                      body: JSON.stringify([
                        {
                          id: 1,
                          holidayName: 'Summer Vacation',
                          startDate: '2024-07-15',
                          endDate: '2024-07-25'
                        }
                      ])
                    });
                  } else {
                    route.fulfill({
                      status: 200,
                      contentType: 'application/json',
                      body: JSON.stringify({})
                    });
                  }
                });

                // Execute pre-actions
                for (const action of pageDef.actions) {
                  await action(page);
                }

                // Navigate to page
                await page.goto(pageDef.url);
                
                // Set theme preference
                await page.evaluate((themeValue) => {
                  localStorage.setItem('theme-preference', themeValue);
                  document.documentElement.setAttribute('data-theme', themeValue);
                  if (themeValue === 'dark') {
                    document.documentElement.classList.add('dark-theme');
                  } else {
                    document.documentElement.classList.remove('dark-theme');
                  }
                }, theme);

                // Wait for page to load
                try {
                  await page.waitForSelector(pageDef.waitFor, { timeout: 15000 });
                  await page.waitForTimeout(2000); // Additional wait for animations
                } catch (error) {
                  console.log(`Warning: Could not find selector ${pageDef.waitFor} for ${pageDef.name}-${theme}`);
                  await page.waitForTimeout(3000); // Still wait a bit
                }

                // Hide scrollbars for cleaner screenshots
                await page.addStyleTag({
                  content: `
                    ::-webkit-scrollbar { display: none; }
                    * { scrollbar-width: none; }
                    body { overflow: hidden; }
                  `
                });

                const screenshotPath = `screenshots/${pageDef.name}-${theme}.png`;
                await page.screenshot({ 
                  path: screenshotPath,
                  fullPage: false,
                  clip: { x: 0, y: 0, width: 1280, height: 720 }
                });
                
                console.log(`Screenshot saved: ${screenshotPath}`);
                await context.close();
              }
            }

            await browser.close();
          }

          takeScreenshots().catch(console.error);
          EOF

      - name: Take screenshots
        working-directory: ./client
        run: node ../take-screenshots.js

      - name: Stop servers
        run: |
          if [ -f backend/backend.pid ]; then
            kill $(cat backend/backend.pid) || true
            rm backend/backend.pid
          fi
          if [ -f client/client.pid ]; then
            kill $(cat client/client.pid) || true
            rm client/client.pid
          fi

      - name: Update README with screenshots
        run: |
          cat << 'EOF' > update-readme.js
          const fs = require('fs');
          
          const readmePath = 'README.md';
          let readme = fs.readFileSync(readmePath, 'utf8');
          
          const screenshotSection = `
          ## Screenshots

          ### Login Page
          | Light Mode | Dark Mode |
          |------------|-----------|
          | ![Login Light](screenshots/login-light.png) | ![Login Dark](screenshots/login-dark.png) |

          ### Clock In/Out Page
          | Light Mode | Dark Mode |
          |------------|-----------|
          | ![Clocking Light](screenshots/clocking-light.png) | ![Clocking Dark](screenshots/clocking-dark.png) |

          ### Holiday Planning Page
          | Light Mode | Dark Mode |
          |------------|-----------|
          | ![Holiday Light](screenshots/holiday-light.png) | ![Holiday Dark](screenshots/holiday-dark.png) |

          *Screenshots are automatically updated on every client code change.*

          `;
          
          const screenshotStartMarker = '## Screenshots';
          const nextSectionMarkers = ['## Setup and Running', '## Development', '## Features', '## API Documentation', '## Contributing', '## License'];
          
          let startIndex = readme.indexOf(screenshotStartMarker);
          if (startIndex !== -1) {
            let endIndex = readme.length;
            
            for (const marker of nextSectionMarkers) {
              const markerIndex = readme.indexOf(marker, startIndex + screenshotStartMarker.length);
              if (markerIndex !== -1 && markerIndex < endIndex) {
                endIndex = markerIndex;
              }
            }
            
            readme = readme.substring(0, startIndex) + readme.substring(endIndex);
          }
          
          // Find insertion point (before "Setup and Running" or at the end)
          let insertIndex = readme.indexOf('## Setup and Running');
          if (insertIndex === -1) {
            insertIndex = readme.indexOf('## Development');
          }
          if (insertIndex === -1) {
            insertIndex = readme.indexOf('## Features');
          }
          if (insertIndex === -1) {
            // Insert before the last section or at the end
            insertIndex = readme.length;
          }
          
          // Insert the screenshot section
          readme = readme.substring(0, insertIndex) + screenshotSection + '\n' + readme.substring(insertIndex);
          
          fs.writeFileSync(readmePath, readme);
          console.log('README.md updated with screenshots');
          EOF
          
          node update-readme.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all screenshots and README changes
          git add screenshots/ README.md
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update screenshots and README [skip ci]"
            git push
          fi

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/
          retention-days: 30
